env:
  browser: false
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  no-unused-vars:
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: false
  # no-console:
  #   - warn  # Allows console statements but warns about them. Change to error to disallow.
  eqeqeq:
    - error
    - always  # Ensures strict equality is used.
  curly:
    - error
    - all
  no-eval:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  brace-style:
    - error
    - 1tbs
  comma-spacing:
    - error
    - before: false
      after: true
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces:
    - error
  space-infix-ops:
    - error
  no-duplicate-imports:
    - error
